// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Das Verhalten von \"long.ToString()\" kann je nach den Gebietsschemaeinstellungen des Benutzers variieren. Ersetzen Sie diesen Aufruf in \"Program.Bot_OnMessage(object, MessageEventArgs)\" durch einen Aufruf an \"long.ToString(IFormatProvider)\".", Justification = "<Ausstehend>", Scope = "member", Target = "~M:covid19bot.Program.Bot_OnMessage(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Die Methode \"void Program.Bot_OnMessage(object sender, MessageEventArgs e)\" übergibt eine Literalzeichenfolge als Parameter \"value\" eines Aufrufs an \"void Console.WriteLine(string value)\". Rufen Sie die folgende(n) Zeichenfolge(n) stattdessen aus einer Ressourcentabelle ab: #### Datenbankverbindung aufgebaut------------{0}.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:covid19bot.Program.Bot_OnMessage(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Aufruf von \"ConfigureAwait\" für erwarteten Task erwägen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:covid19bot.Program.Bot_OnMessage(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Ändern Sie \"Bot_OnMessage\", um spezifischere Ausnahmetypen abzufangen, oder lösen Sie die Ausnahme erneut aus.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:covid19bot.Program.Bot_OnMessage(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2000:Rufen Sie System.IDisposable.Dispose für das von \"new SQLiteCommand(\"select * from AusgangssperrenLK where upper(BUNDESLAND) = upper('\" + cmdlist[2] +\"')\", connection)\" erstellte Objekt auf, bevor alle Verweise darauf außerhalb des gültigen Bereichs liegen.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:covid19bot.Program.Bot_OnMessage(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2100:Überprüfen Sie, ob die in \"Bot_OnMessage\" an \"SQLiteCommand.SQLiteCommand(string commandText, SQLiteConnection connection)\" übergebene Abfragezeichenfolge Benutzereingaben akzeptiert.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:covid19bot.Program.Bot_OnMessage(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2234:Ändern Sie \"Program.Bot_OnMessage(object, MessageEventArgs)\", sodass \"HttpClient.GetAsync(Uri)\" anstelle von \"HttpClient.GetAsync(string)\" aufgerufen wird.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:covid19bot.Program.Bot_OnMessage(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Die Methode \"void Program.Main(string[] args)\" übergibt eine Literalzeichenfolge als Parameter \"value\" eines Aufrufs an \"void Console.WriteLine(string value)\". Rufen Sie die folgende(n) Zeichenfolge(n) stattdessen aus einer Ressourcentabelle ab:  .", Justification = "<Ausstehend>", Scope = "member", Target = "~M:covid19bot.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Der Parameter \"args\" der Methode \"Main\" wird niemals verwendet. Entfernen Sie den Parameter, oder verwenden Sie ihn im Methodentext.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:covid19bot.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2000:Rufen Sie System.IDisposable.Dispose für das von \"new SQLiteCommand(\"INSERT INTO statistics (ID, CHATID, DATETIME, QUERRYTYPE) VALUES (NULL, $chatid, $datetime, $querrytype)\", connection)\" erstellte Objekt auf, bevor alle Verweise darauf außerhalb des gültigen Bereichs liegen.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:covid19bot.Statistics.newQueryLog(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Der Parameter \"url\" der Methode \".ctor\" wird niemals verwendet. Entfernen Sie den Parameter, oder verwenden Sie ihn im Methodentext.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:ShareX_Main_Server.CovidItem.#ctor(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Entfernen Sie die Unterstriche aus dem Namespacenamen \"ShareX_Main_Server\".", Justification = "<Ausstehend>", Scope = "namespace", Target = "~N:ShareX_Main_Server")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1052:Der Typ \"Statistics\" ist ein statischer Containertyp, aber weder \"Static\" noch \"NotInheritable\".", Justification = "<Ausstehend>", Scope = "type", Target = "~T:covid19bot.Statistics")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:\"CovidItem\" ist eine interne Klasse, die offenbar niemals instanziiert wird. Entfernen Sie in diesem Fall den Code aus der Assembly. Wenn diese Klasse nur statische Member enthalten soll, legen Sie sie als \"static\" fest (\"Shared\" in Visual Basic).", Justification = "<Ausstehend>", Scope = "type", Target = "~T:ShareX_Main_Server.CovidItem")]